Added missing require for pathname in spec_helper
Without this, when I ran `rspec` after cloning the project, I got the
following error:

```
An error occurred while loading spec_helper.
Failure/Error: SPEC_ROOT = Pathname(__dir__)

NoMethodError:
  undefined method `Pathname' for main:Object
  # ./spec/spec_helper.rb:22:in `<top (required)>'
```